"""
exp_scale_tasks.py - scaling study requested by the supervisor: 500, 1000, 1500, 2000 and 5000 tasks on a pool of 50
heterogeneous VMs (task lengths uniform 1000-10000 MI, VM speeds 250-2000 MIPS). 10 independent runs per algorithm and
size (the deterministic heuristics run once), 20 000 evaluations per run, population 30, and the algorithm settings of
the earlier studies (V4 baseline, H5, H7) without re-tuning. Descriptive (research_plan_v5.md §29, registered before
the run): no hypothesis test is pre-registered.

  python exp_scale_tasks.py run       # 5 sizes x 14 algorithms x 10 runs -> results/scale_tasks/ (write-once, resumable)
  python exp_scale_tasks.py analyze   # tables -> results/scale_tasks_analysis.md (write-once)
"""
import os, sys
import numpy as np
import pandas as pd
from scipy import stats
from qi_experiment import spec, make_jobs, run_experiment, load_experiment, holm

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.environ.get("QI_RESULTS_DIR", os.path.join(HERE, "results"))
SIZES = [500, 1000, 1500, 2000, 5000]
M, DIST, HET = 50, "uniform", "high"
FAMILIES = [(n, M, DIST, HET) for n in SIZES]
INST_SEEDS = [1]
RUN_SEEDS = list(range(10))
BUDGET, P = 20000, 30
EA = dict(decoherence_c=1.0, exchange=0.5)                  # the (1+1)-EA setting selected in H7 (results/h7_selection.json)
ALGOS = {
    "DMO": spec("run_dmo"), "QI-DMO": spec("run_qidmo", decoherence_c=0.25),
    "MRFO": spec("run_mrfo"), "QI-MRFO": spec("run_qimrfo", decoherence_c=1.0),
    "QI-MRFO+CXM": spec("run_qimrfo", decoherence_c=1.0, exchange=1.0),
    "QI-MRFO+CXM+seed": spec("run_qimrfo", decoherence_c=1.0, exchange=1.0, seed_heuristic="max_min"),
    "GA": spec("run_ga"), "GA+CXM": spec("run_ga", exchange=1.0), "PSO": spec("run_pso"), "Random": spec("run_random"),
    "(1+1)-EA+CXM": spec("run_one_plus_one", **EA), "(1+1)-EA+CXM+seed": spec("run_one_plus_one", **EA, seed_heuristic="max_min"),
    "Max-Min": spec("max_min"), "Min-Min": spec("min_min"),
}
LABELS = {"DMO": "DMO (original)", "QI-DMO": "QI-DMO (quantum-inspired)", "MRFO": "MRFO (original)",
          "QI-MRFO": "QI-MRFO (quantum-inspired)", "QI-MRFO+CXM": "QI-MRFO + swap move", "QI-MRFO+CXM+seed": "QI-MRFO + swap + Max-Min seed",
          "GA": "Genetic Algorithm (GA)", "GA+CXM": "GA + swap move", "PSO": "PSO", "Random": "Random search",
          "(1+1)-EA+CXM": "(1+1)-EA + swap move", "(1+1)-EA+CXM+seed": "(1+1)-EA + swap + Max-Min seed",
          "Max-Min": "Max-Min heuristic", "Min-Min": "Min-Min heuristic"}
COMPARISONS = [("QI-DMO", "DMO"), ("QI-MRFO", "MRFO"), ("QI-MRFO+CXM", "QI-MRFO"), ("QI-MRFO+CXM", "GA"), ("QI-MRFO+CXM", "GA+CXM"),
               ("QI-MRFO+CXM", "(1+1)-EA+CXM"), ("QI-MRFO+CXM+seed", "(1+1)-EA+CXM+seed")]


def jobs():
    return make_jobs("scale_tasks", ALGOS, FAMILIES, INST_SEEDS, RUN_SEEDS, BUDGET, P)


def stage_run():
    run_experiment("scale_tasks", jobs(), config={"sizes": SIZES, "m": M, "dist": DIST, "het": HET, "inst_seeds": INST_SEEDS,
                                                  "run_seeds": RUN_SEEDS, "budget": BUDGET, "P": P, "algos": ALGOS})


def summary(df):
    g = df.groupby(["n", "algo"])
    t = g.agg(runs=("makespan", "size"), mean=("makespan", "mean"), sd=("makespan", "std"), best=("makespan", "min"),
              worst=("makespan", "max"), gap_pct=("gap", "mean"), runtime_s=("runtime_s", "mean"), energy_Wh=("energy_Wh", "mean"))
    t["gap_pct"] *= 100
    t["sd"] = t["sd"].fillna(0.0)
    return t.reset_index()


def analysis_text():
    df = load_experiment("scale_tasks")
    t = summary(df)
    lb = df.groupby("n").lb.first()
    order = list(ALGOS)
    out = ["# Scaling study: 500–5000 tasks on 50 VMs (descriptive)\n",
           "Generated by `python exp_scale_tasks.py analyze` from `results/scale_tasks/records.csv`. One problem per size "
           "(`make_instance(n, 50, seed=1, 'uniform', 'high')`); 10 independent runs per algorithm (heuristics: 1); 20 000 "
           "evaluations per run; population 30. Makespan in seconds (task lengths in MI, VM speeds in MIPS); lower bound = "
           "max(total length / total speed, longest task / fastest VM).\n",
           "## Lower bound per size (s)\n", lb.rename("lower bound (s)").reset_index().to_markdown(index=False, floatfmt=".2f") + "\n"]
    for col, lab, fmt in [("mean", "Makespan (s), mean over runs", ".2f"), ("sd", "Makespan (s), standard deviation", ".2f"),
                          ("best", "Makespan (s), best run", ".2f"), ("worst", "Makespan (s), worst run", ".2f"),
                          ("gap_pct", "Gap to the lower bound (%), mean", ".2f"), ("runtime_s", "Runtime per run (s), mean", ".1f"),
                          ("energy_Wh", "Energy of the final schedule (Wh), mean", ".2f")]:
        pv = t.pivot(index="algo", columns="n", values=col).loc[order]
        pv.index = [LABELS[a] for a in pv.index]
        out.append(f"## {lab}\n"); out.append(pv.to_markdown(floatfmt=fmt) + "\n")
    out.append("## Comparisons (two-sided Mann–Whitney U on the 10 runs per algorithm; Holm across the 5 sizes)\n")
    rows = []
    for a, b in COMPARISONS:
        ps, block = [], []
        for n in SIZES:
            xa = df[(df.n == n) & (df.algo == a)].makespan.values; xb = df[(df.n == n) & (df.algo == b)].makespan.values
            p = stats.mannwhitneyu(xa, xb, alternative="two-sided").pvalue
            ps.append(p); block.append({"A": LABELS[a], "B": LABELS[b], "tasks": n, "mean A (s)": xa.mean(), "mean B (s)": xb.mean(),
                                        "A − B (s)": xa.mean() - xb.mean(), "p": p})
        for r, ph in zip(block, holm(ps)): r["p_holm"] = ph
        rows += block
    out.append(pd.DataFrame(rows).to_markdown(index=False, floatfmt=".4f") + "\n")
    return "\n".join(out)


def stage_analyze():
    path = os.path.join(RES, "scale_tasks_analysis.md")
    if os.path.exists(path):
        raise RuntimeError(f"{path} exists (write-once)")
    txt = analysis_text(); open(path, "w").write(txt); print(txt)


if __name__ == "__main__":
    {"run": stage_run, "analyze": stage_analyze}[sys.argv[1]]()
