"""
exp_h13_event_gamma.py - hypothesis H13 (event-aware decoherence: no decoherence floor after local changes, the default
c = 1 after VM additions) on top of the H12 configuration; derived from the development-seed observation
results/v5_c_dynamic.md, pre-registered in research_plan_v5.md §27 before this script was run. Same harness as H12,
fresh seeds.

After the first epoch the objective is  cost(a) = makespan(a) x (1 + lambda x voluntary migrations / eligible tasks),
relative to the previous DEPLOYED schedule (qi_core.Objective kind 'makespan_migration').

  python exp_h13_event_gamma.py run       # 6 scenarios x 10 FRESH seeds (601-610) x 3 lambdas x 4 strategies
  python exp_h13_event_gamma.py analyze   # statistics -> results/h13_analysis.md

Outputs are new, write-once files: results/h13_event_gamma/, results/h13_analysis.md.
"""
import os, sys
import numpy as np
import pandas as pd
from qi_experiment import run_experiment, load_experiment, run_dyn_job, dyn_job_key, boot_ci, wilcoxon_p, rank_biserial, holm

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.environ.get("QI_RESULTS_DIR", os.path.join(HERE, "results"))
BUDGET0, BUDGET, P, K = 20000, 4000, 30, 8
SEEDS = list(range(601, 611))                       # H6 101-110, H8 201-210, H10 301-310, H11 401-410, H12 501-510
LAMBDAS = [0.05, 0.2, 1.0]
BASE = [dict(name="n100 m10 churn20", n=100, m=10, K=K, change="churn", rho=0.2),
        dict(name="n100 m10 drift", n=100, m=10, K=K, change="drift"),
        dict(name="n100 m10 vm_fail", n=100, m=10, K=K, change="vm_fail"),
        dict(name="n100 m10 vm_add", n=100, m=10, K=K, change="vm_add"),
        dict(name="n100 m10 mixed", n=100, m=10, K=K, change="mixed", rho=0.2),
        dict(name="n200 m20 lognormal mixed", n=200, m=20, K=K, change="mixed", rho=0.2, task_dist="lognormal")]
SCENARIOS = [dict(sc, name=f"{sc['name']} lam={lam}", base=sc["name"], mig_lambda=lam) for lam in LAMBDAS for sc in BASE]
X = {"exchange": 1.0}
H12 = {"algo": "QI-MRFO", "strategy": "continue_struct", "repair": "incremental", "carry_elite": "except_vm_add", "algo_kw": X}
LOCAL = {"churn": 0.0, "drift": 0.0, "vm_fail": 0.0}             # c after local changes; VM additions keep c = 1
STRATEGIES = {
    "Chooser (cheaper of the two)": {"algo": "Chooser"},
    "H12 swarm (c = 1)": dict(H12),
    "H12 swarm, c = 0 after every change": dict(H12, decoherence_by_event=dict(LOCAL, vm_add=0.0)),
    "H12 swarm, event-aware gamma": dict(H12, decoherence_by_event=dict(LOCAL)),
}
def jobs():
    return [{"exp": "h13_event_gamma", "algo": name, "dyn": d, "scenario": sc, "seed": s, "budget0": BUDGET0, "budget": BUDGET, "P": P}
            for sc in SCENARIOS for s in SEEDS for name, d in STRATEGIES.items()]


def stage_run():
    run_experiment("h13_event_gamma", jobs(), runner=run_dyn_job, keyfn=dyn_job_key, sort_cols=["scenario", "algo", "seed"],
                   config={"budget0": BUDGET0, "budget": BUDGET, "P": P, "K": K, "seeds": SEEDS, "lambdas": LAMBDAS,
                           "scenarios": SCENARIOS, "strategies": STRATEGIES})


def paired(df, a, b, metric, by="scenario", scale=100.0):
    rows = []
    w = df[df.algo.isin([a, b])].pivot_table(index=[by, "seed"], columns="algo", values=metric)
    for sc, sub in list(w.groupby(level=0)) + [("ALL", w)]:
        d = (sub[a] - sub[b]).values * scale
        lo, hi = boot_ci(d)
        rows.append({by: sc, "pairs": len(d), "mean A": sub[a].mean() * scale, "mean B": sub[b].mean() * scale, "diff A-B": d.mean(),
                     "CI95 lo": lo, "CI95 hi": hi, "wins A": int((d < 0).sum()), "wins B": int((d > 0).sum()), "p": wilcoxon_p(d), "r_rb": rank_biserial(d)})
    t = pd.DataFrame(rows); msk = t[by] != "ALL"
    t["p_holm"] = np.nan; t.loc[msk, "p_holm"] = holm(t.loc[msk, "p"].values); t.loc[~msk, "p_holm"] = t.loc[~msk, "p"]
    return t


def analysis_text():
    df = load_experiment("h13_event_gamma")
    df["base"] = df.scenario.str.replace(r" lam=.*$", "", regex=True)
    out = ["# H13 analysis — event-aware decoherence (c = 0 after local changes, c = 1 after VM additions) under migration pricing\n",
           "Generated by `python exp_h13_event_gamma.py analyze` from `results/h13_event_gamma/records.csv`. post_cost_gap = mean "
           "over the 8 post-change epochs of (cost - LB) / LB with cost = makespan x (1 + lambda x migrations / eligible); post_gap = "
           "the makespan part alone; migrations = voluntary migrations per epoch. Fresh seeds 601-610. All swarms use the H12 "
           "configuration; the event-aware swarm equals the c = 1 swarm on the VM-addition scenario and the c = 0 swarm on the "
           "churn, drift and VM-failure scenarios by construction.\n"]
    order = list(STRATEGIES)
    for lam in LAMBDAS:
        sub = df[df.mig_lambda == lam]
        out.append(f"## lambda = {lam}\n")
        for metric, label, sc in [("post_cost_gap", "cost gap (%)", 100), ("post_gap", "makespan gap (%)", 100), ("migrations", "voluntary migrations per epoch", 1)]:
            pv = sub.pivot_table(index="base", columns="algo", values=metric, aggfunc="mean")[order] * sc
            out.append(f"### {label}\n"); out.append(pv.round(3).reset_index().to_markdown(index=False, floatfmt=".3f") + "\n")
    out.append("## Pre-registered tests (cost gap; unit = (scenario, seed); Holm across the 6 scenarios within each lambda; ALL = pooled over 60 pairs)\n")
    ev = "H12 swarm, event-aware gamma"
    comps = [(ev, "H12 swarm (c = 1)", "H13a primary: event-aware gamma vs c = 1"),
             (ev, "H12 swarm, c = 0 after every change", "H13b: event-aware gamma vs c = 0 after every change"),
             (ev, "Chooser (cheaper of the two)", "H13c: event-aware gamma vs Chooser"),
             ("H12 swarm, c = 0 after every change", "H12 swarm (c = 1)", "reported: c = 0 after every change vs c = 1")]
    pooled = []
    for lam in LAMBDAS:
        sub = df[df.mig_lambda == lam]
        for a, b, label in comps:
            t = paired(sub, a, b, "post_cost_gap", by="base")
            out.append(f"### {label}, lambda = {lam}: A = {a}, B = {b}\n"); out.append(t.to_markdown(index=False, floatfmt=".4f") + "\n")
            row = t[t.base == "ALL"].iloc[0]; pooled.append({"test": label, "lambda": lam, "diff A-B (pp)": row["diff A-B"], "CI95 lo": row["CI95 lo"],
                                                            "CI95 hi": row["CI95 hi"], "wins A": row["wins A"], "wins B": row["wins B"], "p": row["p"]})
    pt = pd.DataFrame(pooled)
    pt["p_holm (across the 3 lambdas)"] = np.nan
    for label, g in pt.groupby("test"):
        pt.loc[g.index, "p_holm (across the 3 lambdas)"] = holm(g.p.values)
    out.append("## Pooled summary (Holm across the three lambdas within each test)\n"); out.append(pt.to_markdown(index=False, floatfmt=".4f") + "\n")
    return "\n".join(out)


def stage_analyze():
    path = os.path.join(RES, "h13_analysis.md")
    if os.path.exists(path):
        raise RuntimeError(f"{path} exists (write-once)")
    txt = analysis_text(); open(path, "w").write(txt); print(txt)


if __name__ == "__main__":
    {"run": stage_run, "analyze": stage_analyze}[sys.argv[1]]()
