"""
exp_h9_purity_band.py - hypothesis H9 (purity-regulated decoherence, the original report's §21 item 2); design
pre-registered in research_plan_v5.md §18 before this script was run. The band (1, 3) tasks comes from the original
report, so nothing is tuned.

  python exp_h9_purity_band.py test      # the 8 static TEST family shapes x FRESH instance seeds 301-310 x 2 run seeds
  python exp_h9_purity_band.py analyze   # statistics -> results/h9_analysis.md

Outputs are new, write-once files: results/h9_test/, results/h9_analysis.md.
"""
import os, sys
import numpy as np
import pandas as pd
from qi_experiment import spec, make_jobs, run_experiment, load_experiment, paired_table, TEST_FAMILIES, family_name

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.environ.get("QI_RESULTS_DIR", os.path.join(HERE, "results"))
BUDGET, P = 20000, 30
SEEDS = list(range(301, 311))
BAND = [1.0, 3.0]
ALGOS = {"QI-MRFO": spec("run_qimrfo", decoherence_c=1.0),
         "QI-MRFO+band": spec("run_qimrfo", decoherence_c=1.0, move_band=BAND),
         "QI-MRFO+CXM": spec("run_qimrfo", decoherence_c=1.0, exchange=1.0),
         "QI-MRFO+CXM+band": spec("run_qimrfo", decoherence_c=1.0, exchange=1.0, move_band=BAND)}


def stage_test():
    run_experiment("h9_test", make_jobs("h9_test", ALGOS, TEST_FAMILIES, SEEDS, [0, 1], BUDGET, P),
                   config={"band": BAND, "budget": BUDGET, "P": P, "families": [family_name(f) for f in TEST_FAMILIES], "inst_seeds": SEEDS})


def analysis_text():
    df = load_experiment("h9_test")
    out = ["# H9 analysis — purity-regulated decoherence (band 1-3 tasks, from the original report §21)\n",
           "Generated by `python exp_h9_purity_band.py analyze` from `results/h9_test/records.csv` (fresh instance seeds 301-310).\n"]
    for metric, lab, sc in [("gap2", "mean gap2 (%)", 100), ("dup_global_frac", "global duplicate evaluations", 1), ("wasted", "parent-identical candidates", 1),
                            ("c_end", "c = gamma * n at the end of the run", 1), ("c_mean", "mean c over the run", 1), ("move_size", "mean move size (tasks)", 1)]:
        pv = df.pivot_table(index="family", columns="algo", values=metric, aggfunc="mean")[list(ALGOS)] * sc
        out.append(f"## {lab}\n"); out.append(pv.round(4).reset_index().to_markdown(index=False, floatfmt=".4f") + "\n")
    cols = ["family", "pairs", "mean A", "mean B", "diff A-B", "CI95 lo", "CI95 hi", "wins A", "ties", "wins B", "p", "p_holm", "r_rb"]
    for a, b, lab in [("QI-MRFO+band", "QI-MRFO", "H9a (primary, without CXM)"), ("QI-MRFO+CXM+band", "QI-MRFO+CXM", "H9b (under CXM)")]:
        for metric, sc, what in [("dup_global_frac", 100, "duplicate evaluations (percentage points)"), ("gap2", 100, "gap2 (pp); non-inferiority margin +0.10 pp")]:
            t = paired_table(df, a, b, metric=metric, scale=sc)
            out.append(f"### {lab}: {what}; A = {a}, B = {b}\n"); out.append(t[cols].to_markdown(index=False, floatfmt=".4f") + "\n")
    return "\n".join(out) + "\n"


def stage_analyze():
    path = os.path.join(RES, "h9_analysis.md")
    if os.path.exists(path):
        raise RuntimeError(f"{path} exists (write-once)")
    txt = analysis_text(); open(path, "w").write(txt); print(txt)


if __name__ == "__main__":
    {"test": stage_test, "analyze": stage_analyze}[sys.argv[1]]()
