"""
exp_h6_dynamic.py - hypothesis H6 (dynamic re-optimisation: CXM under change x elite carry-over, with migration cost);
design pre-registered in research_plan_v5.md §11 before this script was run.

  python exp_h6_dynamic.py run       # held-out dynamic scenarios (instance seeds 101-110), all strategies
  python exp_h6_dynamic.py analyze   # statistics -> results/h6_analysis.md

Outputs are new, write-once files: results/h6_dynamic/, results/h6_analysis.md.
"""
import os, sys
import numpy as np
import pandas as pd
from qi_experiment import run_experiment, load_experiment, run_dyn_job, dyn_job_key, boot_ci, wilcoxon_p, rank_biserial, holm

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.environ.get("QI_RESULTS_DIR", os.path.join(HERE, "results"))
BUDGET0, BUDGET, P, K = 20000, 4000, 30, 8
SEEDS = list(range(101, 111))
SCENARIOS = [dict(name="n100 m10 churn20", n=100, m=10, K=K, change="churn", rho=0.2),
             dict(name="n100 m10 drift", n=100, m=10, K=K, change="drift"),
             dict(name="n100 m10 vm_fail", n=100, m=10, K=K, change="vm_fail"),
             dict(name="n100 m10 vm_add", n=100, m=10, K=K, change="vm_add"),
             dict(name="n100 m10 mixed", n=100, m=10, K=K, change="mixed", rho=0.2),
             dict(name="n200 m20 lognormal mixed", n=200, m=20, K=K, change="mixed", rho=0.2, task_dist="lognormal")]
X = {"exchange": 1.0}
STRATEGIES = {
    "Max-Min (recompute)": {"algo": "Max-Min"},
    "Incremental (no migration)": {"algo": "Incremental"},
    "GA continue": {"algo": "GA", "strategy": "continue", "repair": "greedy"},
    "GA+CXM continue": {"algo": "GA", "strategy": "continue", "repair": "greedy", "algo_kw": X},
    "QI-MRFO continue": {"algo": "QI-MRFO", "strategy": "continue_struct", "repair": "greedy"},
    "QI-MRFO+CXM continue": {"algo": "QI-MRFO", "strategy": "continue_struct", "repair": "greedy", "algo_kw": X},
    "QI-MRFO continue+elite": {"algo": "QI-MRFO", "strategy": "continue_struct", "repair": "greedy", "carry_elite": True},
    "QI-MRFO+CXM continue+elite": {"algo": "QI-MRFO", "strategy": "continue_struct", "repair": "greedy", "carry_elite": True, "algo_kw": X},
    "P-MRFO+CXM continue+elite": {"algo": "QI-MRFO", "mode": "linear", "strategy": "continue_struct", "repair": "greedy", "carry_elite": True, "algo_kw": X},
    "QI-MRFO+CXM restart": {"algo": "QI-MRFO", "strategy": "restart", "algo_kw": X},
}


def jobs():
    return [{"exp": "h6_dynamic", "algo": name, "dyn": d, "scenario": sc, "seed": s, "budget0": BUDGET0, "budget": BUDGET, "P": P}
            for sc in SCENARIOS for s in SEEDS for name, d in STRATEGIES.items()]


def stage_run():
    run_experiment("h6_dynamic", jobs(), runner=run_dyn_job, keyfn=dyn_job_key, sort_cols=["scenario", "algo", "seed"],
                   config={"budget0": BUDGET0, "budget": BUDGET, "P": P, "K": K, "seeds": SEEDS, "scenarios": SCENARIOS,
                           "strategies": STRATEGIES})


def paired(df, a, b, metric, scale=100.0):
    rows = []
    w = df[df.algo.isin([a, b])].pivot_table(index=["scenario", "seed"], columns="algo", values=metric)
    for sc, sub in list(w.groupby(level=0)) + [("ALL", w)]:
        d = (sub[a] - sub[b]).values * scale
        lo, hi = boot_ci(d)
        rows.append({"scenario": sc, "pairs": len(d), "mean A": sub[a].mean() * scale, "mean B": sub[b].mean() * scale, "diff A-B": d.mean(),
                     "CI95 lo": lo, "CI95 hi": hi, "wins A": int((d < 0).sum()), "wins B": int((d > 0).sum()), "p": wilcoxon_p(d), "r_rb": rank_biserial(d)})
    t = pd.DataFrame(rows); m = t.scenario != "ALL"
    t["p_holm"] = np.nan; t.loc[m, "p_holm"] = holm(t.loc[m, "p"].values); t.loc[~m, "p_holm"] = t.loc[~m, "p"]
    return t


def analysis_text():
    df = load_experiment("h6_dynamic")
    out = ["# H6 analysis — dynamic re-optimisation (CXM under change, elite carry-over, migrations)\n",
           "Generated by `python exp_h6_dynamic.py analyze` from `results/h6_dynamic/records.csv`. post_gap = mean gap to the "
           "(old) lower bound over the 8 post-change epochs; post_auc = mean normalised area under the within-epoch gap curve "
           "(recovery speed); migrations = voluntary task migrations per epoch relative to the previous deployed schedule.\n"]
    order = list(STRATEGIES)
    for metric, label, sc in [("post_gap", "post-change gap (%)", 100), ("post_auc", "recovery AUC (%)", 100),
                              ("migrations", "voluntary migrations per epoch (tasks)", 1), ("post_ratio_mm", "makespan / Max-Min (recompute)", 1)]:
        pv = df.pivot_table(index="scenario", columns="algo", values=metric, aggfunc="mean")[order] * sc
        out.append(f"## {label}\n"); out.append(pv.round(3).reset_index().to_markdown(index=False, floatfmt=".3f") + "\n")
    comps = [("QI-MRFO+CXM continue", "QI-MRFO continue", "post_gap", "H6a primary: CXM under change (post-change gap)"),
             ("QI-MRFO+CXM continue+elite", "QI-MRFO+CXM continue", "post_auc", "H6b: elite carry-over (recovery AUC)"),
             ("QI-MRFO+CXM continue+elite", "QI-MRFO+CXM continue", "post_gap", "H6b secondary: elite carry-over (post-change gap)"),
             ("QI-MRFO continue+elite", "QI-MRFO continue", "post_auc", "elite carry-over without CXM (recovery AUC)"),
             ("QI-MRFO+CXM continue+elite", "GA+CXM continue", "post_gap", "H6c: register swarm vs GA, both with CXM (post-change gap)"),
             ("QI-MRFO+CXM continue+elite", "Max-Min (recompute)", "post_gap", "H6d: vs Max-Min recomputed every epoch (post-change gap)"),
             ("QI-MRFO+CXM continue+elite", "Max-Min (recompute)", "migrations", "H6d: vs Max-Min recomputed every epoch (migrations)"),
             ("QI-MRFO+CXM continue+elite", "QI-MRFO+CXM restart", "post_auc", "value of carried state under CXM (recovery AUC)"),
             ("GA+CXM continue", "GA continue", "post_gap", "CXM on the GA under change (post-change gap)"),
             ("P-MRFO+CXM continue+elite", "QI-MRFO+CXM continue+elite", "post_gap", "classical linear twin vs Born rule under change (post-change gap)")]
    for a, b, metric, label in comps:
        t = paired(df, a, b, metric, scale=(1 if metric == "migrations" else 100))
        out.append(f"### {label}: A = {a}, B = {b}, metric = {metric}\n")
        out.append(t.to_markdown(index=False, floatfmt=".4f") + "\n")
    return "\n".join(out)


def stage_analyze():
    path = os.path.join(RES, "h6_analysis.md")
    if os.path.exists(path):
        raise RuntimeError(f"{path} exists (write-once)")
    txt = analysis_text(); open(path, "w").write(txt); print(txt)


if __name__ == "__main__":
    {"run": stage_run, "analyze": stage_analyze}[sys.argv[1]]()
