"""
exp_h10_elite_migration.py - hypothesis H10 (the deployed schedule as an elite anchor for the register swarm under
migration pricing); design pre-registered in research_plan_v5.md §17 before this script was run. Same harness as H8.

After the first epoch the objective is  cost(a) = makespan(a) x (1 + lambda x voluntary migrations / eligible tasks),
relative to the previous DEPLOYED schedule (qi_core.Objective kind 'makespan_migration').

  python exp_h10_elite_migration.py run       # 6 scenarios x 10 FRESH seeds (301-310) x 3 lambdas x 5 strategies
  python exp_h10_elite_migration.py analyze   # statistics -> results/h10_analysis.md

Outputs are new, write-once files: results/h10_elite_migration/, results/h10_analysis.md.
"""
import os, sys
import numpy as np
import pandas as pd
from qi_experiment import run_experiment, load_experiment, run_dyn_job, dyn_job_key, boot_ci, wilcoxon_p, rank_biserial, holm

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.environ.get("QI_RESULTS_DIR", os.path.join(HERE, "results"))
BUDGET0, BUDGET, P, K = 20000, 4000, 30, 8
SEEDS = list(range(301, 311))                       # H6 used 101-110, H8 201-210
LAMBDAS = [0.05, 0.2, 1.0]
BASE = [dict(name="n100 m10 churn20", n=100, m=10, K=K, change="churn", rho=0.2),
        dict(name="n100 m10 drift", n=100, m=10, K=K, change="drift"),
        dict(name="n100 m10 vm_fail", n=100, m=10, K=K, change="vm_fail"),
        dict(name="n100 m10 vm_add", n=100, m=10, K=K, change="vm_add"),
        dict(name="n100 m10 mixed", n=100, m=10, K=K, change="mixed", rho=0.2),
        dict(name="n200 m20 lognormal mixed", n=200, m=20, K=K, change="mixed", rho=0.2, task_dist="lognormal")]
SCENARIOS = [dict(sc, name=f"{sc['name']} lam={lam}", base=sc["name"], mig_lambda=lam) for lam in LAMBDAS for sc in BASE]
X = {"exchange": 1.0}
STRATEGIES = {
    "Chooser (cheaper of the two)": {"algo": "Chooser"},
    "GA continue": {"algo": "GA", "strategy": "continue", "repair": "greedy"},
    "(1+1)-EA+CXM continue": {"algo": "(1+1)-EA", "strategy": "continue", "repair": "greedy", "algo_kw": {"exchange": 0.5}},
    "QI-MRFO+CXM continue": {"algo": "QI-MRFO", "strategy": "continue_struct", "repair": "greedy", "algo_kw": X},
    "QI-MRFO+CXM continue+elite": {"algo": "QI-MRFO", "strategy": "continue_struct", "repair": "greedy", "carry_elite": True, "algo_kw": X},
}

def jobs():
    return [{"exp": "h10_elite_migration", "algo": name, "dyn": d, "scenario": sc, "seed": s, "budget0": BUDGET0, "budget": BUDGET, "P": P}
            for sc in SCENARIOS for s in SEEDS for name, d in STRATEGIES.items()]


def stage_run():
    run_experiment("h10_elite_migration", jobs(), runner=run_dyn_job, keyfn=dyn_job_key, sort_cols=["scenario", "algo", "seed"],
                   config={"budget0": BUDGET0, "budget": BUDGET, "P": P, "K": K, "seeds": SEEDS, "lambdas": LAMBDAS,
                           "scenarios": SCENARIOS, "strategies": STRATEGIES})


def paired(df, a, b, metric, by="scenario", scale=100.0):
    rows = []
    w = df[df.algo.isin([a, b])].pivot_table(index=[by, "seed"], columns="algo", values=metric)
    for sc, sub in list(w.groupby(level=0)) + [("ALL", w)]:
        d = (sub[a] - sub[b]).values * scale
        lo, hi = boot_ci(d)
        rows.append({by: sc, "pairs": len(d), "mean A": sub[a].mean() * scale, "mean B": sub[b].mean() * scale, "diff A-B": d.mean(),
                     "CI95 lo": lo, "CI95 hi": hi, "wins A": int((d < 0).sum()), "wins B": int((d > 0).sum()), "p": wilcoxon_p(d), "r_rb": rank_biserial(d)})
    t = pd.DataFrame(rows); msk = t[by] != "ALL"
    t["p_holm"] = np.nan; t.loc[msk, "p_holm"] = holm(t.loc[msk, "p"].values); t.loc[~msk, "p_holm"] = t.loc[~msk, "p"]
    return t


def analysis_text():
    df = load_experiment("h10_elite_migration")
    df["base"] = df.scenario.str.replace(r" lam=.*$", "", regex=True)
    out = ["# H10 analysis — the deployed schedule as an elite anchor under migration pricing\n",
           "Generated by `python exp_h10_elite_migration.py analyze` from `results/h10_elite_migration/records.csv`. post_cost_gap = mean over the "
           "8 post-change epochs of (cost - LB) / LB with cost = makespan x (1 + lambda x migrations / eligible); post_gap = the "
           "makespan part alone; migrations = voluntary migrations per epoch. Fresh seeds 301-310.\n"]
    order = list(STRATEGIES)
    for lam in LAMBDAS:
        sub = df[df.mig_lambda == lam]
        out.append(f"## lambda = {lam}\n")
        for metric, label, sc in [("post_cost_gap", "cost gap (%)", 100), ("post_gap", "makespan gap (%)", 100), ("migrations", "voluntary migrations per epoch", 1)]:
            pv = sub.pivot_table(index="base", columns="algo", values=metric, aggfunc="mean")[order] * sc
            out.append(f"### {label}\n"); out.append(pv.round(3).reset_index().to_markdown(index=False, floatfmt=".3f") + "\n")
    out.append("## Pre-registered tests (cost gap; unit = (scenario, seed); Holm across the 6 scenarios within each lambda; ALL = pooled over 60 pairs)\n")
    comps = [("QI-MRFO+CXM continue+elite", "QI-MRFO+CXM continue", "H10a primary: elite anchor"),
             ("QI-MRFO+CXM continue+elite", "Chooser (cheaper of the two)", "H10b: elite-anchored swarm vs Chooser"),
             ("QI-MRFO+CXM continue+elite", "(1+1)-EA+CXM continue", "H10c: vs (1+1)-EA carrying one schedule"),
             ("QI-MRFO+CXM continue+elite", "GA continue", "H10c: vs GA continue"),
             ("QI-MRFO+CXM continue", "Chooser (cheaper of the two)", "replication of H8a on fresh seeds")]
    pooled = []
    for lam in LAMBDAS:
        sub = df[df.mig_lambda == lam]
        for a, b, label in comps:
            t = paired(sub, a, b, "post_cost_gap", by="base")
            out.append(f"### {label}, lambda = {lam}: A = {a}, B = {b}\n"); out.append(t.to_markdown(index=False, floatfmt=".4f") + "\n")
            row = t[t.base == "ALL"].iloc[0]; pooled.append({"test": label, "lambda": lam, "diff A-B (pp)": row["diff A-B"], "CI95 lo": row["CI95 lo"],
                                                            "CI95 hi": row["CI95 hi"], "wins A": row["wins A"], "wins B": row["wins B"], "p": row["p"]})
    pt = pd.DataFrame(pooled)
    pt["p_holm (across the 3 lambdas)"] = np.nan
    for label, g in pt.groupby("test"):
        pt.loc[g.index, "p_holm (across the 3 lambdas)"] = holm(g.p.values)
    out.append("## Pooled summary (Holm across the three lambdas within each test)\n"); out.append(pt.to_markdown(index=False, floatfmt=".4f") + "\n")
    return "\n".join(out)


def stage_analyze():
    path = os.path.join(RES, "h10_analysis.md")
    if os.path.exists(path):
        raise RuntimeError(f"{path} exists (write-once)")
    txt = analysis_text(); open(path, "w").write(txt); print(txt)


if __name__ == "__main__":
    {"run": stage_run, "analyze": stage_analyze}[sys.argv[1]]()
