"""Paired contrasts of every decoherence level against c = 1, with and without CXM (descriptive, development set).

Reads the committed, write-once records of observe_v5_c_under_cxm.py and observe_v5_c_without_cxm.py and writes
results/v5_c_sweep_paired.md (write-once). Pairs = (family, instance seed, run seed) on the 4 development instances,
so the p values are run-level and descriptive; Holm is applied across the comparisons within each host.
"""
import os, sys
_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))   # the repository root
sys.path.insert(0, os.path.join(_ROOT, "src")); os.chdir(_ROOT)   # the qi_* modules; paths below are relative to the root
import os
import pandas as pd
from qi_experiment import boot_ci, wilcoxon_p, holm


def load(exp):
    df = pd.read_csv(os.path.join("results", exp, "records.csv"))
    df["host"] = df.algo.str.split(" c=").str[0]; df["c"] = df.algo.str.split("c=").str[1].astype(float)
    return df


def paired_vs_ref(df, metric, scale, ref=1.0):
    rows = []
    for host, d in df.groupby("host"):
        w = d.pivot_table(index=["family", "inst_seed", "run_seed"], columns="c", values=metric)
        block = []
        for c in [c for c in w.columns if c != ref]:
            diff = (w[c] - w[ref]).values * scale
            lo, hi = boot_ci(diff)
            block.append({"host": host, "c": c, "pairs": len(diff), f"mean at c": w[c].mean() * scale,
                          f"mean at c={ref:g}": w[ref].mean() * scale, "diff": diff.mean(), "CI95 lo": lo, "CI95 hi": hi,
                          "c better": int((diff < 0).sum()), f"c={ref:g} better": int((diff > 0).sum()),
                          "p (run-level)": wilcoxon_p(diff)})
        for r, ph in zip(block, holm([r["p (run-level)"] for r in block])): r["p_holm (within host)"] = ph
        rows += block
    return pd.DataFrame(rows)


if __name__ == "__main__":
    out = ["# Decoherence dose-response: paired contrasts against c = 1 (development set, 10 seeds; descriptive)\n",
           "Generated by `python scripts/observe/analyze_v5_c_sweep.py` from `results/v5_c_under_cxm/records.csv` and "
           "`results/v5_c_without_cxm/records.csv`. diff = metric at c minus metric at c = 1 (percentage points); "
           "pairs = (family, instance seed, run seed) on 4 development instances, so p values are run-level and "
           "descriptive, not a held-out test.\n"]
    for exp, lab in [("v5_c_under_cxm", "with CXM (p_x = 1)"), ("v5_c_without_cxm", "without CXM")]:
        df = load(exp)
        for metric, mlab in [("gap2", "gap2 (%)"), ("dup_global_frac", "global duplicate evaluations (%)")]:
            out.append(f"## {lab}: {mlab}\n")
            out.append(paired_vs_ref(df, metric, 100).to_markdown(index=False, floatfmt=".4f") + "\n")
    path = os.path.join("results", "v5_c_sweep_paired.md")
    assert not os.path.exists(path), f"{path} exists (write-once)"
    open(path, "w").write("\n".join(out)); print("\n".join(out))
