"""V5 OBSERVE (before pre-registering H12): why does the event-aware elite still lose to the Chooser on pure churn?

After churn, repair_schedule only repairs VM failures, so in the carried elite every NEW task inherits the VM of the
departed task that had its index ("slot inheritance"), whatever its length. The Incremental heuristic instead places the
new tasks longest first on the VM that finishes them earliest; new tasks are free to place (not migrations).
Question: at the start of a churn epoch, how far is the slot-inherited elite from the incremental schedule, and does the
swarm (H11 configuration) end above the incremental schedule's cost?

DEVELOPMENT seeds 11-15 only (disjoint from every held-out set: 101-110, 201-210, 301-310, 401-410). Descriptive.
Output: results/v5_churn_elite.md (write-once).
"""
import os, sys
_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))   # the repository root
sys.path.insert(0, os.path.join(_ROOT, "src")); os.chdir(_ROOT)   # the qi_* modules; paths below are relative to the root
import os
import numpy as np
import pandas as pd
from multiprocessing import Pool
from qi_core import Objective
from qi_dynamic import make_dynamic_sequence, run_dynamic, repair_schedule, incremental_list_schedule, map_to_new_vms

SEEDS = list(range(11, 16))
LAMBDAS = [0.05, 0.2, 1.0]
BASE = [dict(name="n100 m10 churn20", n=100, m=10, change="churn", rho=0.2),
        dict(name="n100 m10 mixed", n=100, m=10, change="mixed", rho=0.2)]
K, BUDGET0, BUDGET, P = 8, 20000, 4000, 30


def priced(inst, info, prev, lam):
    ref, forced = map_to_new_vms(prev, info)
    elig = ~forced
    if info["type"] == "churn": elig[info["idx"]] = False
    return Objective(inst, kind="makespan_migration", ref=ref, mig_mask=elig, lam=lam)


def one(args):
    sc, lam, seed = args
    seq = make_dynamic_sequence(sc["n"], sc["m"], seed=seed, K=K, change=sc["change"], rho=sc["rho"])
    out = run_dynamic(seq, "QI-MRFO", "continue_struct", BUDGET0, BUDGET, seed=seed, P=P, decoherence_c=1.0,
                      algo_kw={"exchange": 1.0}, carry_elite="except_vm_add", repair="greedy", mig_lambda=lam)
    rows, rng = [], np.random.default_rng(0)      # neither repair below draws random numbers for churn
    for e in range(1, len(out)):
        inst, info = seq[e]
        if info["type"] != "churn": continue
        prev = out[e - 1]["assign"]; lb = inst.lower_bound(); obj = priced(inst, info, prev, lam)
        slot = repair_schedule(prev, info, inst, rng, "greedy"); inc = incremental_list_schedule(prev, info, inst, rng)
        rows.append({"scenario": sc["name"], "lambda": lam, "seed": seed, "epoch": e,
                     "slot elite cost gap": (obj(slot) - lb) / lb, "incremental cost gap": (obj(inc) - lb) / lb,
                     "swarm end cost gap": (out[e]["cost"] - lb) / lb, "swarm migrations": out[e]["migrations"]})
    return rows


if __name__ == "__main__":
    path = os.path.join("results", "v5_churn_elite.md")
    assert not os.path.exists(path), f"{path} exists (write-once)"
    with Pool(4) as pool:
        df = pd.DataFrame([r for rows in pool.map(one, [(sc, lam, s) for sc in BASE for lam in LAMBDAS for s in SEEDS]) for r in rows])
    df["swarm above incremental"] = df["swarm end cost gap"] > df["incremental cost gap"] + 1e-12
    agg = df.groupby(["scenario", "lambda"]).agg(
        churn_epochs=("epoch", "size"), slot_elite=("slot elite cost gap", "mean"), incremental=("incremental cost gap", "mean"),
        swarm_end=("swarm end cost gap", "mean"), swarm_above_incremental=("swarm above incremental", "mean"),
        swarm_migrations=("swarm migrations", "mean")).reset_index()
    for c in ["slot_elite", "incremental", "swarm_end"]: agg[c] *= 100
    agg["swarm_above_incremental"] *= 100
    txt = ("# V5 observation: the carried elite after churn (development seeds 11-15; descriptive)\n\n"
           "Generated by `python scripts/observe/observe_v5_churn_elite.py`. H11 configuration (QI-MRFO+CXM continue, event-aware elite, "
           "greedy repair). For every churn epoch: priced cost gap (%) of the slot-inherited elite the swarm is given, of the "
           "incremental schedule (new tasks placed longest first, earliest finish; zero voluntary migrations), and of the "
           "swarm's deployed schedule; the share of churn epochs where the swarm ends above the incremental schedule; the "
           "swarm's voluntary migrations per churn epoch.\n\n"
           + agg.rename(columns={"slot_elite": "slot elite (%)", "incremental": "incremental (%)", "swarm_end": "swarm end (%)",
                                 "swarm_above_incremental": "swarm above incremental (% of epochs)"})
               .to_markdown(index=False, floatfmt=".3f") + "\n")
    open(path, "w").write(txt); print(txt)
