"""V5 OBSERVE (before any H13 pre-registration): would a Max-Min recompute be a better elite than the incremental one?

H12's incremental elite still does not beat the Chooser on heavy-tailed n200 mixed at lambda = 0.05, where the Chooser
picks a full Max-Min recompute in most epochs. For the H12 configuration (QI-MRFO+CXM continue, event-aware incremental
elite) on DEVELOPMENT seeds 11-15, at every non-VM-addition epoch: the priced cost gap (%) of the incremental elite, of
the Max-Min recompute (both relative to the swarm's OWN previous schedule), of the cheaper of the two ("Chooser elite")
and of the swarm's deployed schedule; the share of epochs where the recompute is the cheaper candidate and where the
swarm ends above it. Descriptive. Output: results/v5_chooser_elite.md (write-once).
"""
import os, sys
_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))   # the repository root
sys.path.insert(0, os.path.join(_ROOT, "src")); os.chdir(_ROOT)   # the qi_* modules; paths below are relative to the root
import os
import numpy as np
import pandas as pd
from multiprocessing import Pool
from qi_core import Objective, max_min
from qi_dynamic import make_dynamic_sequence, run_dynamic, incremental_list_schedule, map_to_new_vms

SEEDS = list(range(11, 16))
LAMBDAS = [0.05, 0.2, 1.0]
BASE = [dict(name="n100 m10 drift", n=100, m=10, change="drift"),
        dict(name="n100 m10 mixed", n=100, m=10, change="mixed", rho=0.2),
        dict(name="n200 m20 lognormal mixed", n=200, m=20, change="mixed", rho=0.2, task_dist="lognormal")]
K, BUDGET0, BUDGET, P = 8, 20000, 4000, 30


def priced(inst, info, prev, lam):
    ref, forced = map_to_new_vms(prev, info)
    elig = ~forced
    if info["type"] == "churn": elig[info["idx"]] = False
    return Objective(inst, kind="makespan_migration", ref=ref, mig_mask=elig, lam=lam)


def one(args):
    sc, lam, seed = args
    seq = make_dynamic_sequence(sc["n"], sc["m"], seed=seed, K=K, change=sc["change"], rho=sc.get("rho", 0.2),
                                task_dist=sc.get("task_dist", "uniform"))
    out = run_dynamic(seq, "QI-MRFO", "continue_struct", BUDGET0, BUDGET, seed=seed, P=P, decoherence_c=1.0,
                      algo_kw={"exchange": 1.0}, carry_elite="except_vm_add", repair="incremental", mig_lambda=lam)
    rows, rng = [], np.random.default_rng(0)
    for e in range(1, len(out)):
        inst, info = seq[e]
        if info["type"] == "vm_add": continue
        prev = out[e - 1]["assign"]; lb = inst.lower_bound(); obj = priced(inst, info, prev, lam)
        f_inc, f_mm = obj(incremental_list_schedule(prev, info, inst, rng)), obj(max_min(inst))
        rows.append({"scenario": sc["name"], "lambda": lam, "seed": seed, "epoch": e, "type": info["type"],
                     "incremental": (f_inc - lb) / lb, "recompute": (f_mm - lb) / lb, "chooser elite": (min(f_inc, f_mm) - lb) / lb,
                     "swarm end": (out[e]["cost"] - lb) / lb, "recompute cheaper": f_mm < f_inc,
                     "swarm above recompute": out[e]["cost"] > f_mm + 1e-12})
    return rows


if __name__ == "__main__":
    path = os.path.join("results", "v5_chooser_elite.md")
    assert not os.path.exists(path), f"{path} exists (write-once)"
    with Pool(4) as pool:
        df = pd.DataFrame([r for rows in pool.map(one, [(sc, lam, s) for sc in BASE for lam in LAMBDAS for s in SEEDS]) for r in rows])
    agg = df.groupby(["scenario", "lambda"]).agg(
        epochs=("epoch", "size"), incremental=("incremental", "mean"), recompute=("recompute", "mean"),
        chooser_elite=("chooser elite", "mean"), swarm_end=("swarm end", "mean"),
        recompute_cheaper=("recompute cheaper", "mean"), swarm_above_recompute=("swarm above recompute", "mean")).reset_index()
    for c in ["incremental", "recompute", "chooser_elite", "swarm_end", "recompute_cheaper", "swarm_above_recompute"]: agg[c] *= 100
    txt = ("# V5 observation: incremental vs Max-Min recompute as the elite (development seeds 11-15; descriptive)\n\n"
           "Generated by `python scripts/observe/observe_v5_chooser_elite.py`. H12 configuration. Non-VM-addition epochs only; priced cost "
           "gaps (%) relative to the swarm's own previous schedule; shares in % of epochs.\n\n"
           + agg.rename(columns={"incremental": "incremental elite (%)", "recompute": "Max-Min recompute (%)",
                                 "chooser_elite": "cheaper of the two (%)", "swarm_end": "swarm end (%)",
                                 "recompute_cheaper": "recompute cheaper (% of epochs)",
                                 "swarm_above_recompute": "swarm ends above recompute (% of epochs)"})
               .to_markdown(index=False, floatfmt=".3f") + "\n")
    open(path, "w").write(txt); print(txt)
