"""V5 OBSERVE: is the decoherence floor a recovery lever UNDER CHANGE once CXM exists?

The static dose-response is flat for c in [0, 2] under CXM (results/v5_c_sweep_paired.md). Under change the registers
are re-opened by the structural rules and the carried state is partly stale, so gamma could matter again. Dose-response
of c for the recommended migration-priced configuration (QI-MRFO+CXM continue, event-aware elite, repair = REPAIR) on
DEVELOPMENT seeds 11-15 (disjoint from every held-out set), the six H11/H12 scenarios, lambda in {0.05, 0.2, 1.0}.
Descriptive (run-level pairs on 5 seeds); it decides whether an event-aware gamma is worth a pre-registered test.
Output: results/v5_c_dynamic/ (write-once) and results/v5_c_dynamic.md.
"""
import os, sys
_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))   # the repository root
sys.path.insert(0, os.path.join(_ROOT, "src")); os.chdir(_ROOT)   # the qi_* modules; paths below are relative to the root
import os
import pandas as pd
from qi_experiment import run_experiment, run_dyn_job, dyn_job_key, boot_ci, wilcoxon_p, holm

REPAIR = "incremental"                    # the configuration recommended after H12 (research_plan_v5.md §26)
SEEDS = list(range(11, 16))
C_GRID = [0.0, 0.5, 1.0, 2.0, 4.0]
LAMBDAS = [0.05, 0.2, 1.0]
BUDGET0, BUDGET, P, K = 20000, 4000, 30, 8
BASE = [dict(name="n100 m10 churn20", n=100, m=10, K=K, change="churn", rho=0.2),
        dict(name="n100 m10 drift", n=100, m=10, K=K, change="drift"),
        dict(name="n100 m10 vm_fail", n=100, m=10, K=K, change="vm_fail"),
        dict(name="n100 m10 vm_add", n=100, m=10, K=K, change="vm_add"),
        dict(name="n100 m10 mixed", n=100, m=10, K=K, change="mixed", rho=0.2),
        dict(name="n200 m20 lognormal mixed", n=200, m=20, K=K, change="mixed", rho=0.2, task_dist="lognormal")]
SCENARIOS = [dict(sc, name=f"{sc['name']} lam={lam}", base=sc["name"], mig_lambda=lam) for lam in LAMBDAS for sc in BASE]


def jobs():
    return [{"exp": "v5_c_dynamic", "algo": f"QI-MRFO+CXM c={c}",
             "dyn": {"algo": "QI-MRFO", "strategy": "continue_struct", "repair": REPAIR, "carry_elite": "except_vm_add",
                     "algo_kw": {"exchange": 1.0}, "decoherence_c": c},
             "scenario": sc, "seed": s, "budget0": BUDGET0, "budget": BUDGET, "P": P}
            for sc in SCENARIOS for s in SEEDS for c in C_GRID]


if __name__ == "__main__":
    path = os.path.join("results", "v5_c_dynamic.md")
    assert not os.path.exists(path), f"{path} exists (write-once)"
    df = run_experiment("v5_c_dynamic", jobs(), runner=run_dyn_job, keyfn=dyn_job_key, sort_cols=["scenario", "algo", "seed"],
                        config={"note": "development seeds, descriptive", "repair": REPAIR, "c_grid": C_GRID, "seeds": SEEDS,
                                "lambdas": LAMBDAS, "scenarios": SCENARIOS})
    df["c"] = df.algo.str.split("c=").str[1].astype(float)
    df["base"] = df.scenario.str.replace(r" lam=.*$", "", regex=True)
    out = ["# V5 observation: decoherence dose-response under change with CXM (development seeds 11-15; descriptive)\n",
           f"Generated by `python scripts/observe/observe_v5_c_dynamic.py`. QI-MRFO+CXM continue, event-aware elite, repair = {REPAIR}; "
           "post-change cost gap (%) = mean over the 8 post-change epochs. Pairs = (scenario, seed), run-level and "
           "descriptive (5 development seeds).\n"]
    for lam in LAMBDAS:
        sub = df[df.mig_lambda == lam]
        pv = sub.pivot_table(index="base", columns="c", values="post_cost_gap", aggfunc="mean") * 100
        pv.loc["ALL"] = sub.pivot_table(index="c", values="post_cost_gap", aggfunc="mean")["post_cost_gap"] * 100
        out.append(f"## lambda = {lam}: mean post-change cost gap (%) by c\n")
        out.append(pv.round(3).reset_index().to_markdown(index=False, floatfmt=".3f") + "\n")
        w = sub.pivot_table(index=["base", "seed"], columns="c", values="post_cost_gap")
        rows = []
        for c in [c for c in C_GRID if c != 1.0]:
            d = (w[c] - w[1.0]).values * 100
            lo, hi = boot_ci(d)
            rows.append({"c": c, "pairs": len(d), "diff vs c=1 (pp)": d.mean(), "CI95 lo": lo, "CI95 hi": hi,
                         "c better": int((d < 0).sum()), "c=1 better": int((d > 0).sum()), "p (run-level)": wilcoxon_p(d)})
        t = pd.DataFrame(rows); t["p_holm (within lambda)"] = holm(t["p (run-level)"].values)
        out.append(f"### lambda = {lam}: paired contrast against c = 1, pooled over the 6 scenarios\n")
        out.append(t.to_markdown(index=False, floatfmt=".4f") + "\n")
    open(path, "w").write("\n".join(out)); print("\n".join(out))
